cq0_tests:
  sparql_template: 'cq_templates/cq0.sparql'
  parameters:
    cq0_parameter_1: 'Amlodipine'
  expected_output: 'cq_expected_results/cq0_expected_results.json'
uc1_cq1_tests:
  sparql_template: 'cq_templates/uc1_cq1.sparql'
  parameters:
    uc1_cq1_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>'
  expected_output: 'cq_expected_results/uc1_cq1_expected_results.json'
uc1_cq2_tests:
  sparql_template: 'cq_templates/uc1_cq2.sparql'
  parameters:
    uc1_cq2_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>'
  expected_output: 'cq_expected_results/uc1_cq2_expected_results.json'
uc1_cq3_tests:
  sparql_template: 'cq_templates/uc1_cq3.sparql'
  parameters:
    uc1_cq3_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>'
  expected_output: 'cq_expected_results/uc1_cq3_expected_results.json'
uc1_cq3-1_tests:
  sparql_template: 'cq_templates/uc1_cq3-1.sparql'
  parameters:
    uc1_cq3-1_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>'
    uc1_cq3-1_parameter_2: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>'
  expected_output: 'cq_expected_results/uc1_cq3-1_expected_results.json'
uc1_cq4_tests:
  sparql_template: 'cq_templates/uc1_cq4.sparql'
  parameters:
    uc1_cq4_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>'
    uc1_cq4_parameter_2: '<https://spec.pistoiaalliance.org/idmp/ontology/ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities/ExtendedEudraVigilanceMedicinalProductDictionary>'
  expected_output: 'cq_expected_results/uc1_cq4_expected_results.json'
uc1_cq5_tests:
  sparql_template: 'cq_templates/uc1_cq5.sparql'
  parameters:
    uc1_cq5_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/EuropeanUnionClinicalTrialsRegister/AliskirenAsInvestigationalMedicinalProduct>'
  expected_output: 'cq_expected_results/uc1_cq5_expected_results.json'
uc1_cq6_tests:
  sparql_template: 'cq_templates/uc1_cq6.sparql'
  parameters:
    uc1_cq6_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>'
  expected_output: 'cq_expected_results/uc1_cq6_expected_results.json'
uc1_cq7_tests:
  sparql_template: 'cq_templates/uc1_cq7.sparql'
  parameters:
    uc1_cq7_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>'
  expected_output: 'cq_expected_results/uc1_cq7_expected_results.json'
#uc1_cq8_tests:
#  sparql_template: 'cq_templates/uc1_cq8.sparql'
#  parameters:
#    uc1_cq8_parameter_1: 'Norvasc medicinal product'
#  expected_output: 'cq_expected_results/uc1_cq8_expected_results.json'
uc1_cq9_tests:
  sparql_template: 'cq_templates/uc1_cq9.sparql'
  parameters:
    uc1_cq9_parameter_1: '<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>'
  expected_output: 'cq_expected_results/uc1_cq9_expected_results.json'