cq0_tests:
  sparql_template: 'cq_templates/cq0.sparql'
  parameters:
    cq0_parameter_1: 'Amlodipine'
  expected_output: 'cq_expected_results/cq0_expected_results.json'
uc1cq1_tests:
  sparql_template: 'cq_templates/uc1cq1.sparql'
  parameters:
    uc1cq1_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/uc1cq1_expected_results.json'
uc1cq2_tests:
  sparql_template: 'cq_templates/uc1cq2.sparql'
  parameters:
    uc1cq2_parameter_1: 'amlodipine mesylate monohydrate'
  expected_output: 'cq_expected_results/uc1cq2_expected_results.json'
uc1cq3-1a_tests:
  sparql_template: 'cq_templates/cq3-1a.sparql'
  parameters:
    uc1cq3-1a_parameter_1: 'amlodipine mesylate monohydrate'
  expected_output: 'cq_expected_results/uc1cq3-1a_expected_results.json'
uc1cq3-1b_tests:
  sparql_template: 'cq_templates/cq3-1b.sparql'
  parameters:
    uc1cq3-1b_parameter_1: 'amlodipine mesylate monohydrate'
  expected_output: 'cq_expected_results/uc1cq3-1b_expected_results.json'
uc1cq3a_tests:
  sparql_template: 'cq_templates/cq3a.sparql'
  parameters:
    uc1cq3a_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/uc1cq3a_expected_results.json'
uc1cq3b_tests:
  sparql_template: 'cq_templates/cq3b.sparql'
  parameters:
    uc1cq3b_parameter_1: 'amlodipine'
    uc1cq3b_parameter_2: 'terlipressin'
  expected_output: 'cq_expected_results/uc1cq3b_expected_results.json'
uc1cq4-1_tests:
  sparql_template: 'cq_templates/cq4-1.sparql'
  parameters:
    uc1cq4-1_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/uc1cq4-1_expected_results.json'
uc1cq4_tests:
  sparql_template: 'cq_templates/uc1cq4.sparql'
  parameters:
    uc1cq4_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/uc1cq4_expected_results.json'
uc1cq5_tests:
  sparql_template: 'cq_templates/uc1cq5.sparql'
  parameters:
    uc1cq5_parameter_1: 'Norvasc medicinal product'
  expected_output: 'cq_expected_results/uc1cq5_expected_results.json'
uc1cq6_tests:
  sparql_template: 'cq_templates/uc1cq6.sparql'
  parameters:
    uc1cq6_parameter_1: 'amlodipine besylate'
    uc1cq6_parameter_2: 'amlodipine'
  expected_output: 'cq_expected_results/uc1cq6_expected_results.json'
uc1cq7_tests:
  sparql_template: 'cq_templates/uc1cq7.sparql'
  parameters:
    uc1cq7_parameter_1: 'terlipressin acetate'
  expected_output: 'cq_expected_results/uc1cq7_expected_results.json'
uc1cq8_tests:
  sparql_template: 'cq_templates/uc1cq8.sparql'
  parameters:
    uc1cq8_parameter_1: 'Norvasc medicinal product'
  expected_output: 'cq_expected_results/uc1cq8_expected_results.json'
