# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python's dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install robot
      run: |
        sudo wget --no-verbose -m -nH -nd -P /usr/bin https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
        sudo wget --no-verbose -m -nH -nd -P /usr/bin https://github.com/ontodev/robot/releases/latest/download/robot.jar
        sudo chmod +x /usr/bin/robot
    - name: Merge all IDMP ontologies with robot
      run: |
        robot merge --input AboutIDMPDev-ReferenceIndividuals.rdf --output AboutIDMPDev-ReferenceIndividuals.ttl --catalog /home/runner/work/idmp/idmp/catalog-v001.xml
    - name: Run unit tests using rdflib
      run: |
        python etc/unit_tests/unit_test_runner.py --ontology_location /home/runner/work/idmp/idmp/AboutIDMPDev-ReferenceIndividuals.ttl --root_folder /home/runner/work/idmp/idmp/etc/unit_tests/ --cq_source  /home/runner/work/idmp/idmp/etc/CQ/Example/   
        if [ $? != 0 ];
        then
        exit $?
        fi
